export {
  CameraGradient,
  UploadCloud,
  BackArrow,
  Close,
  RightArrow,
  FaceIcon,
  RightIcon,
  ErrorIcon,
  CameraErrorIcon,
  IproovCameraErrorIcon,
  IconApp,
  LolaLogo,
  SuccessIcon,
  CardIcon,
  AddCardIcon,
  RightRoundedIcon,
  HomeAddressIcon,
  WhatsAppIcon,
} from "./icons";
