export {
  CameraGradient,
  UploadCloud,
  BackArrow,
  Close,
  RightArrow,
  FaceIcon,
  RightIcon,
  ErrorIcon,
  CameraErrorIcon,
  IproovCameraErrorIcon,
  IconApp,
  LolaLogo,
  SuccessIcon,
  CardIcon,
  AddCardIcon,
  RightRoundedIcon,
  HomeAddressIcon,
  WhatsAppIcon,
  UploadIcon,
  CreditCardIcon,
  DebitCardIcon,
  BankIcon,
  CashIcon,
  ErrorUserIcon,
  RoundedCheckIcon,
  UserInfokIcon
} from "./icons";
